name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CMake and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Upload binary
        uses: actions/upload-artifact@cded7e8f7a2cf9e638d81c3dc19923a43047de1c
        with:
          name: keystroke_defense_client
          path: build/Release/keystroke_defense_client.exe
